name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
jobs:
  cypress-run:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: ./
		    with:
		      working directory: src/main/java
		      install-component: npm install
    		      build: npm run build
    		      start: npm start
