name: Create Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }} # Specify the tag name for the release
          release_name: Release ${{ github.ref }} 
          body: 'Release notes for v1.0.0'  # Description of the release
          draft: false  # Set to true if you want to create a draft release
          prerelease: false  # Set to true for prerelease versions


